TencentCloudSecret:
  SecretId: "AKIDoQ6b5OtSDjz85v99h39zfAKEsIVXY9oP"
  SecretKey: "Xqyub5XEvNaZN2cFjLxMXYLv8C4kALJ2"

Live:
  PushKey: "f599087597de04d37756e27fb7237243"
  PullKey: "Me4kMHsBjhfRW7yhCDHD"