TencentCloudSecret: # 获取地址 https://console.cloud.tencent.com/cam/capi
  SecretId: "AKIDoQ6b5OtSDjz85v99h39zfAKEsIVXY9oP" # 已废弃，替换成自己的
  SecretKey: "Xqyub5XEvNaZN2cFjLxMXYLv8C4kALJ2" # 已废弃，替换成自己的

Live:
  PushKey: "f599087597de04d37756e27fb7237243" # 已废弃，替换成自己的
  PullKey: "Me4kMHsBjhfRW7yhCDHD" # 已废弃，替换成自己的
